import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import BlogCard from '../components/BlogCard'

const graphCms =  new GraphQLClient('https://api-eu-west-2.hygraph.com/v2/cl9rwb3av1ago01t8gpo0cuir/master');

const QUERY = gql`
{
  posts {
    title
    datePublished
    slug
    content {
      text
    }
    author {
      name
      avatar {
        url
      }
    }
    coverphoto {
      url
    }
    excerpt
  }
}

`

export async function getStaticProps () {
  const {posts} = await graphCms.request(QUERY)

  return {
    props: {
      posts

    },
    revalidate: 10
  }
}

export default function Home({posts}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <main className=" bg-gray-200 absolute left-0 right-0 top-0 flex flex-col items-center gap-10">
        
        <section className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
        {posts.map((post, index) => (
         <BlogCard 
         key={index}
         title={post.title}
         datePublished = {post.author}
         slug = {post.slug}
         content = {post.content}
         author = {post.author}
         coverphoto={post.coverphoto}
         excert={post.excerpt}
         />
         
        ))}
        </section>
        
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
